export function renderSchemaDoc(): string {
  return `# Generated dataset schema

This file is generated by \`pf2data update\`. Do not edit by hand.

## Files

| Path | Contents |
|---|---|
| \`manifest.json\` | Upstream repo and pinned ref, generation timestamp, pack list, creature count, build-time collision set. |
| \`books.json\` | Book catalog: \`pack\`, \`title\`, \`license\`, \`remaster\`, \`creatureCount\`, \`indexPath\`, \`mixed\`. |
| \`index/<pack>.json\` | Search index for one book. Load only the books in use. |
| \`creatures/<pack>/<slug>.json\` | One full creature record. Fetch lazily. |
| \`conditions.json\` | Condition reference text: \`slug\`, \`name\`, \`isValued\`, \`description\`. Reference only -- mechanical effects are hand-implemented in the tracker's rules module. |
| \`glossary.json\` | Monster ability glossary (Grab, Attack of Opportunity, ...): \`slug\`, \`name\`, \`cost\`, \`traits\`, \`description\`. |
| \`traits.json\` | Weapon/action trait and keyword reference (Agile, Deadly, Reach, ...), sourced from \`static/lang/en.json\`'s \`PF2E.TraitDescription*\` keys: \`slug\`, \`name\`, \`description\`. Distinct from \`glossary.json\`, which has nothing for these. |
| \`i18n/fr/**\` | The French overlay. See below. |
| \`SCHEMA.md\` | This file. |

## Index entry fields

\`id\`, \`slug\`, \`name\`, \`level\`, \`rarity\`, \`size\`, \`traits\`, \`ac\`, \`hp\`, \`remaster\`, \`book\`.

## Book catalog fields

\`pack\`, \`title\`, \`license\`, \`remaster\`, \`creatureCount\`, \`indexPath\`. \`title\`/\`license\`/\`remaster\` are decided by the **majority** source among the pack's creatures. \`mixed\` is \`true\` when not every creature in the pack shares that same book/license/remaster -- the tracker should treat such a book as heterogeneous rather than trusting the catalog entry for every creature in it.

## Creature fields

Identity: \`id\` (\`<pack>/<slug>\`), \`foundryId\`, \`name\`, \`level\`, \`rarity\`, \`size\`, \`traits\`, \`source\` (\`pack\`, \`book\`, \`license\`, \`remaster\`).

Defences: \`ac\`, \`acDetails\` (e.g. "25 with shield raised", or \`null\`), \`hp\`, \`hpDetails\` (e.g. "regeneration 20 (deactivated by fire)", or \`null\`), \`saves\` (\`fortitude\`, \`reflex\`, \`will\`, each \`{ value, detail }\` where \`detail\` is flavor text like "+2 vs. poison" or \`null\`), \`immunities\` (\`{ type, exceptions, doubleVs }\`), \`weaknesses\`/\`resistances\` (\`{ type, value, exceptions, doubleVs }\` -- \`exceptions\` is what the resistance/weakness does *not* apply to, e.g. resistance to physical *except* cold iron).

Other statistics: \`perception\`, \`senses\` (\`{ type, acuity, range }\`, e.g. \`{ type: "scent", acuity: "imprecise", range: 30 }\`; \`acuity\`/\`range\` are \`null\` when upstream doesn't specify them), \`languages\`, \`skills\`, \`abilityMods\`, \`speeds\`.

Combat: \`attacks\` (\`name\`, \`kind\`, \`bonus\`, \`damage\` (\`{ formula, type, category }\`, \`category\` is \`"persistent"\`, \`"splash"\`, \`"precision"\` or \`null\`), \`traits\`, \`effects\` (attack-effect slugs like \`"grab"\`, \`"poison"\`)), \`actions\` (\`name\`, \`cost\`, \`category\`, \`traits\`, \`trigger\`, \`requirements\`, \`frequency\`, \`description\`), \`spellcasting\` (\`name\`, \`tradition\`, \`preparation\`, \`dc\`, \`attack\`, \`slots\`, \`spells\`).

Reference: \`gear\`, \`publicNotes\`.

\`cost\` is one of \`1\`, \`2\`, \`3\`, \`reaction\`, \`free\`, \`passive\`.

## French overlay (\`i18n/fr/\`)

\`i18n/fr/index/<pack>.json\` | \`Record<id, string>\` -- creature id -> French
name, for the search index. An id with no French anywhere is OMITTED, never
present with an English or \`null\` value.

\`i18n/fr/creatures/<pack>/<slug>.json\` | one \`CreatureI18n\` per creature:
\`name\`, \`publicNotes\` (nullable), \`actions\` (array of \`{ en, name, description }\`),
\`attacks\` (array of \`{ en, name }\`). \`actions\`/\`attacks\` are index-aligned to
the SAME \`creatures/<pack>/<slug>.json\` arrays, never name-keyed -- 156
creatures carry two Strikes with the same English name (a melee and a thrown
Dagger, Hatchet or Spear), so a name join would silently collapse them onto
one translation. Each overlay entry's \`en\` field records the English name
the translation was built from; \`pf2data verify\` re-checks it against the
live creature file at the same array position on every run, because a
position-based join has no other way to notice that either array's order
drifted between builds -- a silent mismatch would misattribute one action's
French translation to a different action.

\`i18n/fr/conditions.json\` and \`i18n/fr/glossary.json\` | both
\`Record<slug, { name, description | null }>\`, keyed by OUR slug (never
name-keyed, to survive a slug that also collides with a creature or action
name elsewhere in the module). An entry with no French match at all is
OMITTED; one that is only translated by name, with no French body, keeps
\`description: null\`. \`name\` is never null for a present entry -- there is
no such thing as a description-only Babele match.

\`i18n/fr/traits.json\` | \`Record<slug, { name | null, description }>\` --
the same key shape, inverted. Traits come from the French module's own
static \`lang/fr.json\` table, not from Babele: some slugs have a French
body but no \`PF2E.Trait<Suffix>\` display name, so \`name\` is nullable and
\`description\` is not (a trait with no French description at all is
OMITTED rather than represented with an empty or English one).

These three shapes are deliberately asymmetric -- each is honest to what its
own source can and cannot promise, rather than forced into one common
"maybe-translated" record. The app's \`t()\`/name-resolution layer is what
decides the English fallback for any of the gaps above; none of these files
ever bake English text into a French field.

## Notes

- \`remaster\` is per creature, not per repository. Legacy Bestiary 1 and 2 creatures coexist with Monster Core ones by design, because Kingmaker cites them.
- Legacy alignment traits are stripped. \`flat-footed\` is emitted as \`off-guard\`.
- Slug collisions across books are **recorded, not resolved**. Resolution happens in the tracker against the active book set, remaster winning.
- \`@UUID[...]\` and \`@Localize[...]\` placeholders in upstream text are both resolved before emission (localize first, then links, since localized glossary text itself contains \`@UUID\` references). Neither survives into any emitted file.

## Licensing

The English dataset derives from \`foundryvtt/pf2e\`, the Foundry VTT system
repository; each creature's own \`source.license\` records what covers it.

The French overlay derives from \`pathfinder-fr/foundryvtt-pathfinder2-fr\`
(module \`pf2-fr\`), a fan translation that is openly licensed and
independent of Black Book Editions -- the commercial publisher of the
French PRINTED books. **No text transcribed from BBE's printed books may be
committed to this public repo.** This constrains more than the pipeline:
during Task 17 of the French-localisation work, French names for the last 30
untranslated creatures were briefly sourced by transcribing them from the
printed books and committed (\`a668d3f\`), then backed out before that commit
ever left the local machine, once recognised as redistributing BBE's
translation. All 30 were instead resolved from \`pf2-fr\`'s own retired
\`archive/\` directory -- still fan-module content, joined by Foundry item id
-- which is why \`stages/archive.ts\` and the archive fallback in
\`stages/i18n.ts\` exist. No BBE-sourced text is committed anywhere in this
repo.

## Pinning

There are two independent pins in \`manifest.json\`: \`upstreamRef\` (the
English \`foundryvtt/pf2e\` checkout) and \`frRef\` (the French \`pf2-fr\`
checkout). \`pf2data update --latest\` moves BOTH pins to their current HEAD
in the same run -- one flag, deliberately, since the person running this is
the only operator and a second flag to move just one pin would be ceremony
with no user. \`pf2data update\` with no \`--latest\` reuses whichever refs
are already pinned.

If a pin is missing (an empty \`frRef\` means "never pinned" -- the field
only exists from the version that added the French overlay on, so an older
manifest carries \`""\` and must be treated as absent rather than checked
out as a ref) and \`--latest\` is not given, the run fails with
\`No pinned ref: data/manifest.json has no "<field>" for <repo>. Run with
--latest to create one.\` -- naming the SPECIFIC manifest field
(\`upstreamRef\` or \`frRef\`) and the specific repo it pins, not a generic
message shared by both checks, so the two failure modes are distinguishable.

## CLI exit codes

| Code | Meaning |
|---|---|
| 0 | Success, no change |
| 10 | Success, data updated |
| 20 | Verification failed |
| 30 | Upstream or network error |
| 1 | Usage error |

Exit code \`20\` means verification failed; run \`pf2data verify\` for details.

Structured JSON is written to stdout when stdout is not a TTY. Human-readable output always goes to stderr.
`;
}
