export function renderSchemaDoc(): string {
  return `# Generated dataset schema

This file is generated by \`pf2data update\`. Do not edit by hand.

## Files

| Path | Contents |
|---|---|
| \`manifest.json\` | Upstream repo and pinned ref, generation timestamp, pack list, creature count, build-time collision set. |
| \`books.json\` | Book catalog: \`pack\`, \`title\`, \`license\`, \`remaster\`, \`creatureCount\`, \`indexPath\`. |
| \`index/<pack>.json\` | Search index for one book. Load only the books in use. |
| \`creatures/<pack>/<slug>.json\` | One full creature record. Fetch lazily. |
| \`conditions.json\` | Condition reference text: \`slug\`, \`name\`, \`isValued\`, \`description\`. Reference only -- mechanical effects are hand-implemented in the tracker's rules module. |
| \`glossary.json\` | Monster ability glossary (Grab, Attack of Opportunity, ...): \`slug\`, \`name\`, \`cost\`, \`traits\`, \`description\`. |
| \`SCHEMA.md\` | This file. |

## Index entry fields

\`id\`, \`slug\`, \`name\`, \`level\`, \`rarity\`, \`size\`, \`traits\`, \`ac\`, \`hp\`, \`remaster\`, \`book\`.

## Creature fields

Identity: \`id\` (\`<pack>/<slug>\`), \`foundryId\`, \`name\`, \`level\`, \`rarity\`, \`size\`, \`traits\`, \`source\` (\`pack\`, \`book\`, \`license\`, \`remaster\`).

Defences: \`ac\`, \`hp\`, \`saves\` (\`fortitude\`, \`reflex\`, \`will\`), \`immunities\`, \`weaknesses\`, \`resistances\`.

Other statistics: \`perception\`, \`senses\`, \`languages\`, \`skills\`, \`abilityMods\`, \`speeds\`.

Combat: \`attacks\` (\`name\`, \`kind\`, \`bonus\`, \`damage\`, \`traits\`), \`actions\` (\`name\`, \`cost\`, \`category\`, \`traits\`, \`trigger\`, \`requirements\`, \`frequency\`, \`description\`), \`spellcasting\` (\`name\`, \`tradition\`, \`preparation\`, \`dc\`, \`attack\`, \`slots\`, \`spells\`).

Reference: \`gear\`, \`publicNotes\`.

\`cost\` is one of \`1\`, \`2\`, \`3\`, \`reaction\`, \`free\`, \`passive\`.

## Notes

- \`remaster\` is per creature, not per repository. Legacy Bestiary 1 and 2 creatures coexist with Monster Core ones by design, because Kingmaker cites them.
- Legacy alignment traits are stripped. \`flat-footed\` is emitted as \`off-guard\`.
- Slug collisions across books are **recorded, not resolved**. Resolution happens in the tracker against the active book set, remaster winning.

## CLI exit codes

| Code | Meaning |
|---|---|
| 0 | Success, no change |
| 10 | Success, data updated |
| 20 | Verification failed |
| 30 | Upstream or network error |
| 1 | Usage error |

Exit code \`20\` means verification failed; run \`pf2data verify\` for details.

Structured JSON is written to stdout when stdout is not a TTY. Human-readable output always goes to stderr.
`;
}
